dist: trusty
sudo: required
language: python
python:
- '3.6'
services:
- docker
script:
- docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
- docker pull akariv/nominatim-israel || true
- "./build.sh"
env:
  global:
  - secure: n57zrhracdpdB3jd+M1O5VFDMGSBrUp5Lf8KNTWlVu6UQsnmFPfagmpY5TVLGv1zqq2dSsi8q4ZUjN4XD0N5cSJsItUi20v8J0BRoxza8l/lrFHFcaP3NqKvfiSm52kuv1405nAovMnTBgROqFiNKaANAGVRUAb/4etmStm0cOjzmmRgpEbfsQHO0Y4AgUl0GIfMokUIUmCCbEDJSv/BBa+UAMAkEKZOeZn8XXXbTOVb53bJRuzXDAOdlUHV7VujPCdKv3u7jTxwUOHbadnQHuOAwKCnD3F/4iJROqBtTkCHe2GEmY276KJYzfY3iGoeTzpoqw8T3YWNKixq8n6vblwqg4ZcYdhE5bmbjFYQvbTlyHvHduPt2Zh6JGXcMOnDikLDW+6cKnUMFaWpwsLj5cFNb7PAg2Sy9VD4aAxQMJlAAsi2p5r0E5uwK8vmMnzvu6yLuq6WDEiUZMAi6alP22WPsKTUyddkTwz4k70Mrvh+uiNXPSK7tVu3+eZD6DRGDI0UqzdBUwPUBJ8zVR5KmLU3gItBTSKtQbGVC8WxQFK9/l7cfK01VUsH1uLGa/Bw6Krlx0wfDI3fBbVmzg8sIefATob2TqceQVll2ajELttn/B0jTbmqmT6tDk1jlS+VN734WGifeMqpOWVoV+/lJinadAIH7xm1lDu/G9N5afM=
  - secure: KOxGw0rQTeXVOfeaRVt0U5q12g2RrsSLLuMu91SNilONifqpIQJzscl44u3qD10ygu9Ckc6ZSy/v/w1KPROTRq/6tYaomIQiWb1dURYxQVnRfQibx8zIUJ7ekeHbX6i7jsfWFsMBCkhgoT/Tc//Mnlcpc6v0AZRx0m2/J7nqEQh4yBDKcoqcdbUVIRoNZm6BP075XTG2ERH+tYBP29G9kALS/RthDb88+wFRvC6dsageyxLak6naWw1E4nh2oAyd1xPFx/XK/uzEw1V16CMzSO6VK/aGEsRECWQhyw7AicaaO+nGa31uEDlB/BAfGPRMU0oChZu8GcWPSojFc8Cj/GgYsAlR9QVe5QGEiv5McjfsxsrItanb6fOpBICpKa5XeQCDTZaTOrJGub9EBP+mDPPpsEzYn+33dAEBTrC1jvvjDDvQ2TP3vM4Dr7iACS9rtkj4rFUjYS+vQwwYz0q74rs5f3nlHWquFQaJ5/wtcX3Mr22/T//8YUydTv8VI+w5AgpVcVQiTrK8kfSFlIczgCnY1UZcvZ9IxPZ5LIxmRtg+ARlwfUAAb+Hfoeg/C3ekqOY4PnxG9Mf73/L/Olhpo2A7rElpHHnUDaUxdANPFna46n0YxkQntLNq9czhXvcoYu3vEUwHJ6WRkPmcJou1o1tNaBh1EKWN8lU9FyRE6Rs=
